### PR TITLE
fix(sync): fixed skipping docker images when they already synced

### PR DESCRIPTION
**Pull request by peusebiu**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
https://github.com/project-zot/zot/issues/1490

**What does this PR do / Why do we need it**:
currently docker images are downloaded every time, because comparison between remote and local is done before conversion of docker images to oci.
convert docker manifests to oci manifests before syncing, compare with local one and skip if it's already synced

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**
no

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pmirshad** [comment]
Thank you for doing this. I was debugging the same behavior as https://github.com/project-zot/zot/issues/1490 when mirroring from Amazon ECR (on-demand). Came across your PR as I was hacking in this support.

**Review by andaaron — APPROVED** [review]

**Comment by peusebiu** [comment]
> Thank you for doing this. I was debugging the same behavior as #1490 when mirroring from Amazon ECR (on-demand). Came across your PR as I was hacking in this support.

Hello @pmirshad do you want to independently test this patch?

**Review by rchincha — APPROVED** [review]
lgtm

**Comment by pmirshad** [comment]
> Hello @pmirshad do you want to independently test this patch?

I had patched in your changes over the latest `main` and was running it for the past two days. Works as expected. Log snippet from today.

```
{"level":"info","repository":"alpine","reference":"3.13","goroutine":817,"caller":"zotregistry.io/zot/pkg/api/routes.go:1736","time":"2023-06-22T10:34:49.656152094Z","message":"trying to get updated image by syncing on demand"}
{"level":"info","goroutine":819,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:433","time":"2023-06-22T10:34:49.656326359Z","message":"getting available client"}
{"level":"info","remote":"https://<ecr-endpoint>","repo":"alpine","reference":"3.13","goroutine":819,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:244","time":"2023-06-22T10:34:49.672344378Z","message":"sync: syncing image"}
{"level":"info","image":"<ecr-endpoint>/alpine:3.13","goroutine":819,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:418","time":"2023-06-22T10:34:50.129544448Z","message":"skipping image because it's already synced"} <<<<
{"level":"info","image":"<ecr-endpoint>/alpine:3.13","goroutine":819,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:421","time":"2023-06-22T10:34:50.129757627Z","message":"sync: finished syncing image"}
...
{"level":"info","module":"http","clientIP":"<ip>","method":"HEAD","path":"/v2/alpine/manifests/3.13?ns=<ecr-endpoint>","statusCode":200,"latency":"0s","bodySize":0,"headers":{"Accept":["application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*"],"User-Agent":["containerd/1.4.13"]},"goroutine":817,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-06-22T10:34:50.33479259Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"<ip>","method":"GET","path":"/v2/alpine/manifests/sha256:2fefe8f7522d4db9e4a67f2efa41fcad31cd6544c21b787c5dacde72c1734563?ns=<ecr-endpoint>","statusCode":200,"latency":"0s","bodySize":405,"headers":{"Accept":["application/vnd.oci.image.manifest.v1+json, */*"],"Accept-Encoding":["gzip"],"User-Agent":["containerd/1.4.13"]},"goroutine":843,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-06-22T10:34:50.349163883Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"<ip>","method":"GET","path":"/v2/alpine/blobs/sha256:76ae9b81aa35ceec6534c5202c06e7a207dd10b073602d0a7479d1da03422a80?ns=<ecr-endpoint>","statusCode":200,"latency":"0s","bodySize":585,"headers":{"Accept":["application/vnd.oci.image.config.v1+json, */*"],"Accept-Encoding":["gzip"],"User-Agent":["containerd/1.4.13"]},"goroutine":843,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-06-22T10:34:50.369382419Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"<ip>","method":"GET","path":"/v2/alpine/blobs/sha256:4e9f2cdf438714c2c4533e28c6c41a89cc6c1b46cf77e54c488db30ca4f5b6f3?ns=<ecr-endpoint>","statusCode":200,"latency":"0s","bodySize":2814079,"headers":{"Accept":["application/vnd.oci.image.layer.v1.tar+gzip, */*"],"Accept-Encoding":["gzip"],"User-Agent":["containerd/1.4.13"]},"goroutine":843,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-06-22T10:34:50.406012831Z","message":"HTTP API"}
```

Thanks again 👍🏼

**Pull request merged**
