### PR TITLE
WIP: Azure Blob Storage implementation

### PR DESCRIPTION
**Pull request by jkroepke**
# Blocked by

*  https://github.com/project-zot/zot/pull/2532

---

**What type of PR is this?**

feature

**Which issue does this PR fix**:

#2221 

**What does this PR do / Why do we need it**:

Native support for Azure blob storage

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note
Native support for Azure Blob storage
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jkroepke** [comment]
This PR is marked as WIP, since it depends on the distribution v3 packages which is not released yet.

**Comment by peusebiu** [comment]
Hello @jkroepke Isn't it possbile to reuse the s3 driver? and make it more generic. in theory it should work with all major cloud providers.

**Comment by jkroepke** [comment]
>  in theory it should work with all major cloud providers.

In practice, there is no S3 Compatibility API at Azure. The distribution project maintain an azure driver which I re-use here:

https://github.com/distribution/distribution/blob/main/docs/content/storage-drivers/azure.md

**Comment by peusebiu** [comment]
> > in theory it should work with all major cloud providers.
> 
> In practice, there is no S3 Compatibility API at Azure. The distribution project maintains an azure driver which I re-use here:
> 
> https://github.com/distribution/distribution/blob/main/docs/content/storage-drivers/azure.md
> 
> If upstream distribution project nativly support Azure, it should not be a major issue for zot? I thought, zot fully depends on it and the usage for storage driver is transparent.

I see, understood, ok.

**Comment by rchincha** [comment]
Let's target this for v2.1.0

**Comment by jkroepke** [comment]
> Let's target this for v2.1.0

A requirement for this PR would be `github.com/docker/distribution` v3.0.0-alpha.1 or higher. Thats something that should not be part of the PR here.

**Comment by rchincha** [comment]
@jkroepke I think you can make progress on this one now?

**Comment by jkroepke** [comment]
> @jkroepke I think you can make progress on this one now?

I will do, but sadly it does not work out of the box and I have to investigate here whats going wrong.

Using Azure Tables as remote cache will be done in a separate PR.

**Comment by rchincha** [comment]
@jkroepke do you have an update on this? or need any assistance?

**Comment by jkroepke** [comment]
Hey @rchincha 

Sorry, but I have other priorities that I need to address, and it might take a while before I can return to this.

**Comment by rchincha** [comment]
@jkroepke any updates on this? This would be useful for you and for the community at large.

**Comment by jkroepke** [comment]
Hi @rchincha 

After reviewing #2584 and #724, I need to pause any further community work for now. Our initial tests did not cover signatures, but the lack of signature support could potentially cause issues in future scenarios.

**Pull request closed without merging**
