### PR TITLE
feat: add a kind cluster example

### PR DESCRIPTION
**Pull request by rchincha**
Add examples/kind-with-registry.sh to start a kind cluster with zot as a local registry.

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
```
$ examples/kind-with-registry.sh
Unable to find image 'ghcr.io/project-zot/zot-minimal-linux-amd64:latest' locally
latest: Pulling from project-zot/zot-minimal-linux-amd64
383e1c5dd0c1: Pull complete
c59673e9fae3: Pull complete
80225d9fa5dd: Pull complete
6384eab72842: Pull complete
2773140e4fcd: Pull complete
Digest: sha256:d6436e1d9dab3256987bf3882277d7413366cc10cf46e72b82df146c48509b14
Status: Downloaded newer image for ghcr.io/project-zot/zot-minimal-linux-amd64:latest
0dd6f7c73431152994295b8fbc862584f667daaa0efbe9a06724c0d922be8e4f
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️ c
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
configmap/local-registry-hosting created
```

**Comment by rchincha** [comment]
```
$ skopeo copy --format=oci --dest-tls-verify=false docker://gcr.io/google-samples/hello-app:1.0 docker://localhost:5001/hello-app:1.0

$ kubectl create deployment hello-server --image=localhost:5001/hello-app:1.0
deployment.apps/hello-server created
```

**Comment by rchincha** [comment]
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m1s                   default-scheduler  Successfully assigned default/hello-server-6b9695fc99-5sc4q to kind-control-plane
  Normal   Pulling    3m25s (x4 over 5m)     kubelet            Pulling image "localhost:5001/hello-app:1.0"
  Warning  Failed     3m25s (x4 over 5m)     kubelet            Failed to pull image "localhost:5001/hello-app:1.0": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5001/hello-app:1.0": failed to resolve reference "localhost:5001/hello-app:1.0": unexpected status code [manifests 1.0]: 503 Service Unavailable
  Warning  Failed     3m25s (x4 over 5m)     kubelet            Error: ErrImagePull
  Warning  Failed     3m14s (x6 over 4m59s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m1s (x7 over 4m59s)   kubelet            Back-off pulling image "localhost:5001/hello-app:1.0"

 ```

**Comment by rchincha** [comment]
```
$ export no_proxy=$no_proxy,kind-registry

$ kubectl create deployment hello-server --image=localhost:5001/hello-app:1.0

$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
hello-server-6b9695fc99-c4xwh   1/1     Running   0          18s
```

**Comment by rchincha** [comment]
Just verifying that it is indeed zot where images are getting pushed/pulled from

```
$ docker ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS         PORTS                       NAMES
9ab0da8dcdf5   kindest/node:v1.21.1                                 "/usr/local/bin/entr…"   3 minutes ago   Up 3 minutes   127.0.0.1:40907->6443/tcp   kind-control-plane732467724b3e   ghcr.io/project-zot/zot-minimal-linux-amd64:latest   "/usr/local/bin/zot-…"   3 minutes ago   Up 3 minutes   127.0.0.1:5001->5000/tcp    kind-registry

{"level":"info","module":"http","clientIP":"172.20.0.2:47662","method":"GET","path":"/v2/hello-app/blobs/sha256:fbad7aa519f7da86dde82ab83e3130d8024e9ffebc315cead1fecb230e208340?ns=localhost%3A5001","statusCode":200,"latency":"0s","bodySize":799928,"headers":{"Accept":["application/vnd.oci.image.layer.v1.tar+gzip, */*"],"Accept-Encoding":["gzip"],"User-Agent":["containerd/v1.5.2"]},"goroutine":76,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-04-19T07:07:04.439605445Z","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"172.20.0.2:47652","method":"GET","path":"/v2/hello-app/blobs/sha256:fda4ba87f6fbeebb651625814b981d4100a98c224fef80d562fb33853500f40e?ns=localhost%3A5001","statusCode":200,"latency":"0s","bodySize":8004672,"headers":{"Accept":["application/vnd.oci.image.layer.v1.tar+gzip, */*"],"Accept-Encoding":["gzip"],"User-Agent":["containerd/v1.5.2"]},"goroutine":93,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-04-19T07:07:04.451260679Z","message":"HTTP API"}
```

**Review by andaaron — APPROVED** [review]
LGTM, but I am not an expert in kind.

**Pull request merged**
