### PR TITLE
feat(sync): skip already synced images in sync ondemand

### PR DESCRIPTION
**Pull request by peusebiu**
**What type of PR is this?**

**Which issue does this PR fix**:
#1208

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
Thanks for your work,I have tested it and seems like it's still copying image always.

```shell
oem@lan:~/repo/git/zot$ bin/zot-linux-amd64 -v
{"level":"info","distribution-spec":"1.1.0-dev","commit":"v2.0.0-rc2-33-g3d6d340","binary-type":"-sync-search-scrub-metrics-lint-ui","go version":"go1.20","time":"2023-03-03T23:52:29+08:00","message":"version"}
```

Pull image :

```
docker pull localhost:8081/kube-apiserver:v1.25.2
docker pull localhost:8081/kube-apiserver:v1.25.2
```

config:
```json
{
    "distspecversion":"1.1.0-dev",
    "storage": {
        "rootDirectory": "/tmp/zot_to_sync",
        "dedupe": false,
        "gc": false
    },
    "http": {
        "address": "127.0.0.1",
        "port": "8081"
    },
    "log": {
        "level": "debug"
    },
    "extensions": {
        "sync": {
            "registries": [
                {
                    "urls": [
                        "https://k8s.m.daocloud.io"
                    ],
                    "onDemand": true,
                    "tlsVerify": false,
                    "PollInterval": "30s"
                }
            ]
        },
        "scrub": {
            "interval": "24h"
        }
    }
}
```

**Review by liangyuanpeng — APPROVED** [review]
Have tested for the feature and it's working for me. Thanks for your work.  :)

**Review by andaaron — DISMISSED** [review]
LGTM

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
