### PR TITLE
fix: Allow docker client to push/pull

### PR DESCRIPTION
**Pull request by brianwilkinson**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brianwilkinson** [comment]
I was getting this problem:
`$ docker push localhost:5000/alpine:latest
The push refers to repository [localhost:5000/alpine]
f1417ff83b31: Pushed 
manifest invalid: manifest invalid
`

**Comment by rchincha** [comment]
Pls. see https://github.com/project-zot/zot/issues/724 for more discussion about this topic.

**Comment by brianwilkinson** [comment]
I closing this as it's obviously flying in the face of zot design to make it work this way

**Comment by willzhang** [comment]
same here with v1.4.3
```
root@ubuntu:~# docker push 192.168.72.16:5000/ubuntu:latest
The push refers to repository [192.168.72.16:5000/ubuntu]
256d88da4185: Layer already exists 
manifest invalid: manifest invalid
```

**Pull request closed without merging**
