### PR TITLE
fix(conformance): OCI-Filters-Applied should return a literal

### PR DESCRIPTION
**Pull request by rchincha**
https://github.com/opencontainers/distribution-spec/issues/448

Should only indicate what filter-type was applied and not what exact values it was filtered on.

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by andaaron — DISMISSED** [review]
LGTM

**Comment by andaaron** [comment]
If you rebase that zap scan failure should go away.

**Comment by rchincha** [comment]
Let me coordinate with Brandon about this PR

**Comment by rchincha** [comment]
[FAILED] Expected
      <string>: artifactType
  to equal
      <string>: application/vnd.nhl.peanut.butter.bagel
  In [It] at: /home/runner/work/zot/zot/distribution-spec/conformance/03_discovery_test.go:326 @ 07/21/23 21:05:21.231
  
  ^ this should really be the only failure if we plan to merge this.

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Review by andaaron — APPROVED** [review]

**Pull request merged**
