### PR TITLE
fix(deps): bump go mods

### PR DESCRIPTION
**Pull request by wuhuizuo**
**What type of PR is this?**
cleanup

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:
1. update distribution dep to support S3-compatible services (ref: https://github.com/distribution/distribution/pull/4291)
2. update the github.com/gorilla/mux: the issue was solved.

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note
None
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
@wuhuizuo can you pls rebase and resubmit

**Comment by wuhuizuo** [comment]
> @wuhuizuo can you pls rebase and resubmit
Sorry for late response, I have solved the CI task problems.

**Comment by jkroepke** [comment]
See also #2532

**Comment by andaaron** [comment]
Hi @wuhuizuo, #2532 was merged in the meantime, can we close this?

**Pull request closed without merging**
