### PR TITLE
Report unknown keys when parsing configuration files

### PR DESCRIPTION
**Pull request by peusebiu**
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
@peusebiu can you add some test code to demonstrate this?

**Comment by peusebiu** [comment]
> @peusebiu can you add some test code to demonstrate this?

Tried to do it today but I don't know how to check commands errors in testing, because we exit with panic(err) and the output doesn't get set.

```
		args := []string{"verify", tmpfile.Name()}
		cmd := cli.NewServerRootCmd()
		buff := bytes.NewBufferString("")
		cmd.SetOut(buff)
		cmd.SetErr(buff)
		cmd.SetArgs(args)

		defer func(c C) {
			err := recover()
			// buff is empty
			t.Logf("buff: %s", buff.String())
			c.So(buff.String(), ShouldContainSubstring, "config doesn't contain any key:value pair")
			c.So(err, ShouldBeNil)
		}(c)

		err = cmd.Execute()
```

**Comment by rchincha** [comment]
> > @peusebiu can you add some test code to demonstrate this?
> 
> @rchincha
> 
> Tried to do it today but I don't know how to check commands errors in testing, because we exit with panic(err) and the output doesn't get set.
> 
> Here buff is empty:
> 
> ```
> 		args := []string{"verify", tmpfile.Name()}
> 		cmd := cli.NewServerRootCmd()
> 		buff := bytes.NewBufferString("")
> 		cmd.SetOut(buff)
> 		cmd.SetErr(buff)
> 		cmd.SetArgs(args)
> 
> 		defer func(c C) {
> 			err := recover()
> 			// buff is empty
> 			t.Logf("buff: %s", buff.String())
> 			c.So(buff.String(), ShouldContainSubstring, "config doesn't contain any key:value pair")
> 			c.So(err, ShouldBeNil)
> 		}(c)
> 
> 		err = cmd.Execute()
> ```
> 
> So is there a way to check the output of zot verify? Didn't find anything in cobra docs.

There is a ShouldPanic()
https://github.com/smartystreets/goconvey/issues/108
^ if it helps

**Review by rchincha — DISMISSED** [review]
lgtm

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
