### PR TITLE
Migrate from docker/build-push-action to stacker-build-push-action

### PR DESCRIPTION
**Pull request by peusebiu**
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by peusebiu** [comment]
sample running: https://github.com/peusebiu/zot/runs/5992826936?check_suite_focus=true

**Comment by rchincha** [comment]
This looks good, but where the "build-args" changes made to stacker-build-push-action?

**Comment by peusebiu** [comment]
> This looks good, but where the "build-args" changes made to stacker-build-push-action?

I made a PR there and merged it, look there.

**Comment by rchincha** [comment]
`
$ ls Dockerfile*

Dockerfile  Dockerfile-conformance  Dockerfile-minimal  Dockerfile-zb  Dockerfile-zxp
`

Why not the -conformance one?

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
