### PR TITLE
Add a job to check zot config examples (and fix existing examples)

### PR DESCRIPTION
**Pull request by andaaron**
Rebase and fix coverage issues in https://github.com/project-zot/zot/pull/2215.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
CI failures?

**Comment by andaaron** [comment]
> CI failures?

Do you want me to signoff the cherry-picked commit with the original author's email?
I was thinking we squash and merge anyway from GH UI.

**Comment by rchincha** [comment]
DCO check is complaining about:
https://github.com/project-zot/zot/pull/2322/commits/ab82db4d5497f3eb5729fb8ac835352eb9c576e0

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
