### PR TITLE
fix: images command not truncating image name/tag 

### PR DESCRIPTION
**Pull request by aokirisaki**
Signed-off-by: Lisca Ana-Roberta <ana.kagome@yahoo.com>

**What type of PR is this?**

**Which issue does this PR fix**:
#823 

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aokirisaki** [comment]
output without the --fullName flag:
```
IMAGE NAME                        TAG                       DIGEST        SIZE      
busybox                           latest                    b9590ac9      773kB     
busybox                           new                       b9590ac9      773kB     
busybox                           1.0.1                     2ac88360      773kB     
golang                            1.18                      d45a1013      353MB     
hello-artifact                    v2                        74470033      12B       
python                            latest                    e8e1d47c      351MB     
test-regclient                    latest                    d66fe387      76MB      
test-regclient                    1.0.0                     d8be8fb7      76MB      
test-truncate-redis-long-name...  latest                    e533a641      42MB      
test-truncate-redis-long-name...  long-tag-to-test-trun...  e533a641      42MB      
zot-chart/zot                     0.1.0                     cf8cd347      2.3kB     
zot-cve-test                      0.0.1                     98f02d9e      75MB      
zot-test                          0.0.1                     d66fe387      76MB  
```

**Comment by rchincha** [comment]
Make "fullName" behavior the default
and remove the truncated behavior entirely.

**Review by andaaron — APPROVED** [review]
LGTM

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
