### PR TITLE
misc: make update_licenses.sh faster

### PR DESCRIPTION
**Pull request by jkroepke**
**What type of PR is this?**

misc

**Which issue does this PR fix**:

update_licenses.sh is slow

**What does this PR do / Why do we need it**:

On a Mac M1, the total execution time goes down from 12:37 to 4:51

```
./scripts/update_licenses.sh  1138.82s user 109.82s system 164% cpu 12:37.23 total
./scripts/update_licenses.sh  1394.44s user 209.08s system 550% cpu 4:51.27 total
```

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andaaron** [comment]
The change itself looks good to me. Please update the commit message.

**Comment by jkroepke** [comment]
Should be good for now

**Review by rchincha — APPROVED** [review]
lgtm

**Comment by rchincha** [comment]
From recent runs, for example https://github.com/project-zot/zot/pull/2594
vast swathes of the license file is getting deleted. So something is broken.

**Comment by jkroepke** [comment]
I had only such crazy behavior, If I'm running the script before running go mod tidy.

**Pull request merged**
