### PR TITLE
docs: Fix Examples Readme to use proper field `repositories` instead of `repoNames`

### PR DESCRIPTION
**Pull request by ericgraf**
**What type of PR is this?**

Documentation

**Which issue does this PR fix**:

N/A

**What does this PR do / Why do we need it**:

Fix documentation to use proper field called repositories instead of repoNames. This looks like an accidental mix up with the variable name used in code vs configuration field in this change  https://github.com/project-zot/zot/pull/1866 .

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

None this is a documentaion change.

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

Nope only a documentation change.

**Does this PR introduce any user-facing change?**:

```release-note
Fix Examples Readme to use correct field storage.retention.policies.repositories.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by andaaron — DISMISSED** [review]

**Comment by rchincha** [comment]
@ericgraf can you pls. fix the CI failures?

Commit msgs should begin with "docs: ..." and pls (GPG) sign your commits.

**Comment by rchincha** [comment]
@ericgraf sorry, needs some clarification.
The actual git commit msg has to begin as "docs: ..." for each one here:
https://github.com/project-zot/zot/pull/2074/commits

After that, 
`git rebase -S --signoff -i HEAD~2`

**Comment by ericgraf** [comment]
@rchincha Let me know if there is anything else I missed.

**Comment by rchincha** [comment]
@ericgraf One last one nitpick which is tripping the DCO check.

sign-off not found for commit author: ericgraf eric.j.graf@gmail.com; found: ['ericgraf <eric@giantswarm.io>']

Your git.config.email is somehow different vs `git commit --sign-off`?

**Comment by andaaron** [comment]
Hi @ericgraf, please use `git commit --amend -s -S`, and repush.
Please make sure you use the same email address for the commit author and the GPG signing, and that email address is associated with your GH account in your GH account settings.

**Pull request merged**
