### PR TITLE
test: refactor CVE tests in CLI package

### PR DESCRIPTION
**Pull request by andaaron**
cli tests: remove redundant conveys in CVE tests
cli tests: reduce duration of CVE tests by reducing the number of DB downloads

Signed-off-by: Andrei Aaron <aaaron@luxoft.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
Why are these tests redundant?

**Comment by andaaron** [comment]
> Why are these tests redundant?

Changes are:

A.
There were nested conveys following the pattern:
- outer convey was a positive test
- inner conveys were negative tests
The positive and negative tests did not depend on one another, but the positive test was repeated for each negative test.

So for example if there was 1 positive test and 2 negative tests what go would do is:
1. execute the outer convey with the positive test
2. execute the 1st inner convey with the 1st negative test
3. execute the outer convey with the positive test
4. execute the 2nd inner convey with the 2nd negative test

Since there were no dependencies between these tests they can be moved on the same level.

B.
The test function bringin up the controller for `TestServerCVEResponseGQL` was the same for `TestServerCVEResponse`, so I removed `TestServerCVEResponseGQL` and moved the Conveys under `TestServerCVEResponse`. This will save time on the initial TrivyDB download, since it's done only once when the controller starts.

C. The `Convey("without flags", func() {` was actually the same as the test under which it was nested: `Convey("Test CVE invalid url port", t, func() {` no code differences so I removed it.

As can be seen in the coverage report there are no changes, as this PR just moves the code to make it more readable (also in test execution output) and efficient, it does not change the test logic.

**Comment by andaaron** [comment]
Rebased and update commit message with info above.

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
