### PR TITLE
add PageInfo to GlobalSearch and RepoListWithNewestImage results

### PR DESCRIPTION
**Pull request by alexstan12**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andaaron** [comment]
@alexstan12 this PR should be against the integration branch on @laurentiuNiculae's repo.

**Comment by andaaron** [comment]
This is actually implemented on the integration branch.

**Comment by alexstan12** [comment]
@andaaron this was merged before on ui_integration_andrei, but the PR was kept for when we'll merge it in main. At least that was the discussion at the time.

**Comment by andaaron** [comment]
Ok, open the PR after the initial work in https://github.com/project-zot/zot/pull/979 is merged.

**Pull request closed without merging**
